apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: application
  labels:
    app: employees
    component: frontend
spec:
  replicas: 3
  selector:
    matchLabels:
      app: employees
  template:
    metadata:
      labels:
        app: employees
        component: frontend
    spec:
      containers:
        - name: application-container
          image: 570629616813.dkr.ecr.us-east-1.amazonaws.com/app-image-clo835-kubernetes-assignment:latest
          env:
            - name: DBPWD
              value: pw
            - name: DBUSER
              value: root
            - name: DBHOST
              value: "mysql.database.svc.cluster.local"
            - name: DBPORT
              value: "3306"
          ports:
            - containerPort: 8080
      imagePullSecrets:
        - name: regcred