apiVersion: v1
kind: Service
metadata:
  name: colorapp
  labels:
    name: colorapp
    component: frontend
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30000
  selector:
    name: colorapp