apiVersion: v1
kind: Pod
metadata:
  name: mysql-pod
spec:
  containers:
    - name: mysql-container
      image: 570629616813.dkr.ecr.us-east-1.amazonaws.com/database-image-clo835-docker-assignment:latest
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: pw
        - name: MYSQL_DATABASE
          value: employees
        - name: MYSQL_USER
          value: root
        - name: MYSQL_PASSWORD
          value: pw
      ports:
        - containerPort: 3306
      
